name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

     strategy:
      matrix:
        version: ['12.x', '8.6.0', '8.16.2']

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js v${{matrix.version}}
      uses: actions/setup-node@v1
      with:
        node-version: ${{matrix.version}}
    - name: NPM install, build, and test
      run: |
        npm install
        npm test
      env:
        CI: true
        ON_PREM_META_HOST: test.local:8443
        ON_PREM_META_APITOKEN: yourtoken
